on:
   push:
     branches:
       - master
name: release-please
jobs:
 release-please:
   runs-on: ubuntu-latest
   steps:
     - uses: GoogleCloudPlatform/release-please-action@v3.1.2
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         release-type: node
         bump-minor-pre-major: Yes
